<?php

// Generated by `php artisan schema:squash` on 2026-09-01T20:24:24+00:00.
// Blueprint-only recreation of the live schema, safe to run against
// SQLite (or any Schema-facade-supported driver) for the standalone
// demo build. Do not hand-edit — regenerate instead.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {

        Schema::create('before_after_pairs', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('page_id')->nullable();
            $table->smallInteger('sort_order')->default('0');
            $table->text('narrative');
            $table->bigInteger('before_image_id')->nullable();
            $table->bigInteger('after_image_id')->nullable();
            $table->text('before_prompt');
            $table->text('after_transformation_prompt');
            $table->string('status', 16)->default('draft');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->index(['site_id', 'page_id'], 'before_after_pairs_site_id_page_id_index');
        });

        Schema::create('business_profiles', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->json('profile_data');
            $table->string('model_used', 255)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('layout_fingerprint')->nullable();
            $table->timestamp('layout_fingerprint_updated_at')->nullable();
            $table->boolean('has_visual_portfolio')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->unique(['site_id'], 'business_profiles_site_id_unique');
        });

        Schema::create('cache', function (Blueprint $table) {
            $table->string('key', 255);
            $table->text('value');
            $table->bigInteger('expiration');
            $table->primary(['key']);
            $table->index(['expiration'], 'cache_expiration_index');
        });

        Schema::create('cache_locks', function (Blueprint $table) {
            $table->string('key', 255);
            $table->string('owner', 255);
            $table->bigInteger('expiration');
            $table->primary(['key']);
            $table->index(['expiration'], 'cache_locks_expiration_index');
        });

        Schema::create('clients', function (Blueprint $table) {
            $table->id('id');
            $table->string('name', 255);
            $table->string('slug', 255);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->bigInteger('cid')->nullable();
            $table->unique(['cid'], 'clients_cid_unique');
            $table->unique(['slug'], 'clients_slug_unique');
        });

        Schema::create('editor_agent_approvals', function (Blueprint $table) {
            $table->uuid('id');
            $table->string('kind', 255);
            $table->bigInteger('site_id');
            $table->bigInteger('requested_by_user_id')->nullable();
            $table->string('requested_by_identifier', 255);
            $table->bigInteger('approved_by_user_id')->nullable();
            $table->string('approved_by_identifier', 255)->nullable();
            $table->string('channel', 16);
            $table->string('grant_principal', 255);
            $table->string('operation', 64);
            $table->string('args_hash', 64);
            $table->json('summary');
            $table->timestamp('requested_at');
            $table->timestamp('approved_at')->nullable();
            $table->timestamp('denied_at')->nullable();
            $table->timestamp('consumed_at')->nullable();
            $table->timestamp('expires_at');
            $table->primary(['id']);
            $table->index(['grant_principal', 'site_id', 'channel', 'operation', 'args_hash'], 'editor_approvals_lookup_index');
            $table->index(['site_id', 'expires_at'], 'editor_approvals_site_expiry_index');
        });

        Schema::create('editor_operation_log', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('page_id')->nullable();
            $table->bigInteger('actor_user_id')->nullable();
            $table->string('actor_channel', 16);
            $table->string('operation', 64);
            $table->string('result_code', 32);
            $table->integer('duration_ms')->default(0);
            $table->timestamp('created_at')->useCurrent();
            $table->string('subject_type', 32)->nullable();
            $table->string('subject_ref', 128)->nullable();
            $table->index(['actor_user_id', 'created_at'], 'editor_operation_log_actor_user_id_created_at_index');
            $table->index(['site_id', 'created_at'], 'editor_operation_log_site_id_created_at_index');
        });

        Schema::create('external_api_calls', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id')->nullable();
            $table->string('provider', 16);
            $table->string('endpoint', 32);
            $table->smallInteger('http_status')->nullable();
            $table->json('request')->nullable();
            $table->json('response_meta')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->index(['site_id', 'created_at'], 'external_api_calls_site_id_created_at_index');
        });

        Schema::create('failed_jobs', function (Blueprint $table) {
            $table->id('id');
            $table->string('uuid', 255);
            $table->text('connection');
            $table->text('queue');
            $table->text('payload');
            $table->text('exception');
            $table->timestamp('failed_at')->useCurrent();
            $table->unique(['uuid'], 'failed_jobs_uuid_unique');
        });

        Schema::create('fx_rates', function (Blueprint $table) {
            $table->id('id');
            $table->string('base', 3);
            $table->string('quote', 3);
            $table->decimal('rate', 18, 8);
            $table->date('rate_date');
            $table->string('source', 255)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->index(['base', 'quote', 'rate_date'], 'fx_rates_base_quote_rate_date_index');
            $table->unique(['base', 'quote', 'rate_date'], 'fx_rates_base_quote_rate_date_unique');
        });

        Schema::create('generated_page_revisions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('page_id');
            $table->json('content_data');
            $table->boolean('ai_generated')->default(false);
            $table->string('ai_model_version', 255)->nullable();
            $table->text('ai_prompt_used')->nullable();
            $table->bigInteger('created_by_user_id')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->bigInteger('parent_revision_id')->nullable();
            $table->index(['page_id', 'created_at'], 'generated_page_revisions_page_id_created_at_index');
            $table->index(['parent_revision_id'], 'generated_page_revisions_parent_revision_id_index');
        });

        Schema::create('generated_pages', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('page_type', 255);
            $table->json('content_data');
            $table->integer('version')->default(1);
            $table->string('model_used', 255)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('nav_label', 30)->nullable();
            $table->smallInteger('sort_order')->default('0');
            $table->timestamp('archived_at')->nullable();
            $table->bigInteger('draft_revision_id')->nullable();
            $table->bigInteger('published_revision_id')->nullable();
            $table->string('status', 16)->default('published');
            $table->string('hero_source', 255)->default('shared');
            $table->string('footer_label', 60)->nullable();
            $table->string('personalise_override', 16)->default('inherit');
            $table->timestamp('deleted_at')->nullable();
            $table->string('kind', 32)->nullable();
            $table->string('origin', 32)->default('pipeline');
            $table->string('layout_preset_key', 64)->nullable();
            $table->bigInteger('parent_id')->nullable();
            $table->integer('structure_epoch')->default(0);
            $table->index(['site_id', 'archived_at'], 'generated_pages_site_id_archived_at_index');
            $table->index(['site_id', 'kind'], 'generated_pages_site_id_kind_index');
            $table->index(['site_id', 'page_type'], 'generated_pages_site_id_page_type_index');
            $table->index(['status'], 'generated_pages_status_index');
        });

        Schema::create('hero_versions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('page_type', 255);
            $table->string('url', 255);
            $table->string('watermark_url', 255)->nullable();
            $table->text('prompt')->nullable();
            $table->string('model', 255)->nullable();
            $table->json('placement')->nullable();
            $table->boolean('is_active')->default(false);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('slot', 16)->default('hero');
            $table->boolean('upgrade_candidate')->default(false);
            $table->string('source', 20)->default('ai_generated');
            $table->timestamp('deleted_at')->nullable();
            // SKIPPED partial index hero_versions_active_by_run_slot_unique (Blueprint cannot express a WHERE predicate)
            // SKIPPED partial index hero_versions_one_active_per_slot (Blueprint cannot express a WHERE predicate)
            $table->index(['site_id', 'page_type', 'is_active'], 'hero_versions_project_id_page_type_is_active_index');
        });

        Schema::create('hero_video_versions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('s3_key', 500);
            $table->text('prompt')->nullable();
            $table->string('provider', 80)->nullable();
            $table->string('resolution', 8)->nullable();
            $table->smallInteger('duration_secs')->nullable();
            $table->string('source', 16)->default('ai_generated');
            $table->json('metadata')->nullable();
            $table->boolean('is_active')->default(false);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'created_at'], 'hero_video_versions_site_id_created_at_index');
            $table->index(['site_id', 'is_active'], 'hero_video_versions_site_id_is_active_index');
        });

        Schema::create('imported_media', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('source', 32);
            $table->string('external_id', 128);
            $table->string('url', 1024);
            $table->integer('width')->nullable();
            $table->integer('height')->nullable();
            $table->text('caption')->nullable();
            $table->timestamp('imported_at');
            $table->string('assigned_to', 32)->nullable();
            $table->bigInteger('assigned_page_id')->nullable();
            $table->json('placement')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->index(['site_id', 'assigned_to'], 'imported_media_site_assigned_idx');
            $table->unique(['site_id', 'source', 'external_id'], 'imported_media_site_source_external_unique');
            $table->index(['source'], 'imported_media_source_index');
        });

        Schema::create('job_batches', function (Blueprint $table) {
            $table->string('id', 255);
            $table->string('name', 255);
            $table->integer('total_jobs');
            $table->integer('pending_jobs');
            $table->integer('failed_jobs');
            $table->text('failed_job_ids');
            $table->text('options')->nullable();
            $table->integer('cancelled_at')->nullable();
            $table->integer('created_at');
            $table->integer('finished_at')->nullable();
            $table->primary(['id']);
        });

        Schema::create('jobs', function (Blueprint $table) {
            $table->id('id');
            $table->string('queue', 255);
            $table->text('payload');
            $table->smallInteger('attempts');
            $table->integer('reserved_at')->nullable();
            $table->integer('available_at');
            $table->integer('created_at');
            $table->index(['queue'], 'jobs_queue_index');
        });

        Schema::create('layout_presets', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('key', 64);
            $table->string('label', 255);
            $table->text('description')->nullable();
            $table->json('recipe');
            $table->string('status', 16)->default('draft');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('page_kind', 16)->default('service');
            $table->unique(['site_id', 'page_kind', 'key'], 'layout_presets_site_id_page_kind_key_unique');
        });

        Schema::create('logo_concepts', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('source', 255);
            $table->string('path', 255);
            $table->integer('rank')->nullable();
            $table->integer('score')->nullable();
            $table->boolean('is_selected')->default(false);
            $table->json('metadata')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->integer('version')->default(0);
            $table->timestamp('deleted_at')->nullable();
            $table->text('prompt')->nullable();
            $table->string('quality', 20)->nullable();
            // SKIPPED partial index logo_concepts_one_selected_per_site (Blueprint cannot express a WHERE predicate)
            $table->index(['site_id', 'is_selected'], 'logo_concepts_project_id_is_selected_index');
            $table->index(['site_id', 'source'], 'logo_concepts_project_id_source_index');
            $table->index(['site_id', 'version'], 'logo_concepts_site_id_version_index');
        });

        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email', 255);
            $table->string('token', 255);
            $table->timestamp('created_at')->nullable();
            $table->primary(['email']);
        });

        Schema::create('previews', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('slug', 255);
            $table->string('theme', 255);
            $table->json('snapshot');
            $table->boolean('is_active')->default(true);
            $table->timestamp('published_at');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->unique(['slug'], 'previews_slug_unique');
        });

        Schema::create('project_categories', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('name', 255);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['site_id', 'name'], 'project_categories_site_id_name_unique');
        });

        Schema::create('project_items', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('page_id')->nullable();
            $table->string('type', 16);
            $table->integer('sort_order')->default(0);
            $table->string('status', 16)->default('draft');
            $table->string('source', 32)->default('ai_generated');
            $table->string('category', 64);
            $table->string('title', 120);
            $table->string('description', 280);
            $table->bigInteger('image_id')->nullable();
            $table->json('metrics')->nullable();
            $table->json('metadata')->nullable();
            $table->string('content_hash', 40);
            $table->string('media_hash', 40);
            $table->string('image_job_state', 16)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('published_snapshot')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->bigInteger('detail_page_id')->nullable();
            $table->bigInteger('category_id')->nullable();
            $table->index(['site_id', 'page_id'], 'project_items_site_id_page_id_index');
            $table->index(['site_id', 'status'], 'project_items_site_id_status_index');
            $table->index(['site_id', 'type', 'sort_order'], 'project_items_site_id_type_sort_order_index');
        });

        Schema::create('projects_page_drafts', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('content_hash', 40);
            $table->json('response');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['created_at'], 'projects_page_drafts_created_at_index');
            $table->unique(['site_id', 'content_hash'], 'projects_page_drafts_site_id_content_hash_unique');
        });

        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id', 255);
            $table->bigInteger('user_id')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->text('payload');
            $table->integer('last_activity');
            $table->primary(['id']);
            $table->index(['last_activity'], 'sessions_last_activity_index');
            $table->index(['user_id'], 'sessions_user_id_index');
        });

        Schema::create('shop_cart_items', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('cart_id');
            $table->bigInteger('variant_id');
            $table->integer('qty');
            $table->integer('unit_price_cents');
            $table->bigInteger('reservation_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('personalisation')->nullable();
            $table->string('personalisation_hash', 40)->default('');
            $table->unique(['cart_id', 'variant_id', 'personalisation_hash'], 'shop_cart_items_cart_id_variant_id_personalisation_hash_unique');
        });

        Schema::create('shop_carts', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('session_cookie_id', 255);
            $table->bigInteger('customer_id')->nullable();
            $table->string('email', 255)->nullable();
            $table->timestamp('last_active_at')->useCurrent();
            $table->timestamp('abandoned_at')->nullable();
            $table->bigInteger('converted_order_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'session_cookie_id'], 'shop_carts_site_id_session_cookie_id_index');
        });

        Schema::create('shop_categories', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('slug', 255);
            $table->string('name', 255);
            $table->text('description')->nullable();
            $table->integer('sort_order')->default(0);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('hero_image_url', 2048)->nullable();
            $table->string('hero_alt', 255)->nullable();
            $table->string('hero_height', 255)->default('medium');
            $table->smallInteger('bg_position_y')->default('50');
            $table->string('text_zone', 255)->default('middle-left');
            $table->text('hero_prompt')->nullable();
            $table->string('hero_model', 255)->nullable();
            $table->bigInteger('parent_id')->nullable();
            $table->string('path', 255)->default('');
            $table->smallInteger('depth')->default('1');
            $table->boolean('is_anchor')->default(true);
            $table->string('visibility', 16)->default('visible');
            $table->string('meta_title', 70)->nullable();
            $table->string('meta_description', 170)->nullable();
            $table->string('sort', 20)->default('manual');
            $table->text('description_long')->nullable();
            $table->json('faqs')->nullable();
            $table->boolean('is_ai_seeded')->default(false);
            $table->string('hero_width', 16)->default('boxed');
            $table->boolean('hero_enabled')->default(true);
            $table->string('hero_mode', 16)->nullable();
            $table->string('hero_text_style', 16)->nullable();
            $table->string('hero_accent_word', 60)->nullable();
            $table->boolean('intro_band')->default(false);
            $table->index(['site_id', 'parent_id'], 'shop_categories_site_id_parent_id_index');
            $table->unique(['site_id', 'path'], 'shop_categories_site_id_path_unique');
            $table->unique(['site_id', 'slug'], 'shop_categories_site_id_slug_unique');
        });

        Schema::create('shop_customer_addresses', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('customer_id');
            $table->string('label', 40)->nullable();
            $table->string('name', 255);
            $table->string('phone', 255)->nullable();
            $table->string('line1', 255);
            $table->string('line2', 255)->nullable();
            $table->string('city', 255);
            $table->string('region', 255)->nullable();
            $table->string('postcode', 16);
            $table->string('country_code', 2);
            $table->boolean('is_default_shipping')->default(false);
            $table->boolean('is_default_billing')->default(false);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'customer_id'], 'shop_customer_addresses_site_id_customer_id_index');
        });

        Schema::create('shop_customer_magic_links', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('customer_id');
            $table->string('token_hash', 255);
            $table->string('requested_ip', 255)->nullable();
            $table->timestamp('expires_at');
            $table->timestamp('consumed_at')->nullable();
            $table->string('consumed_ip', 255)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['customer_id', 'expires_at'], 'shop_customer_magic_links_customer_id_expires_at_index');
        });

        Schema::create('shop_customers', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('email', 255);
            $table->string('name', 255)->nullable();
            $table->string('password_hash', 255)->nullable();
            $table->timestamp('email_verified_at')->nullable();
            $table->timestamp('marketing_consent_at')->nullable();
            $table->timestamp('terms_accepted_at')->nullable();
            $table->timestamp('last_login_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['site_id', 'email'], 'shop_customers_site_id_email_unique');
        });

        Schema::create('shop_drafts', function (Blueprint $table) {
            $table->bigInteger('site_id');
            $table->integer('catalogue_revision')->default(0);
            $table->bigInteger('updated_by_user_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->primary(['site_id']);
        });

        Schema::create('shop_featured_products', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('product_id');
            $table->integer('sort_order')->default(0);
            $table->timestamp('starts_at')->nullable();
            $table->timestamp('ends_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'starts_at', 'ends_at'], 'shop_featured_products_site_id_starts_at_ends_at_index');
        });

        Schema::create('shop_hero_versions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('scope', 255);
            $table->bigInteger('scope_id')->nullable();
            $table->string('image_url', 2048);
            $table->string('hero_alt', 255)->nullable();
            $table->string('model_used', 128)->nullable();
            $table->bigInteger('created_by_user_id')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->index(['site_id', 'scope', 'scope_id'], 'shop_hero_versions_site_id_scope_scope_id_index');
        });

        Schema::create('shop_inventory_movements', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('variant_id');
            $table->integer('delta');
            $table->string('reason', 32);
            $table->string('reference_type', 255)->nullable();
            $table->bigInteger('reference_id')->nullable();
            $table->text('note')->nullable();
            $table->timestamp('created_at');
            $table->index(['variant_id', 'created_at'], 'shop_inventory_movements_variant_id_created_at_index');
        });

        Schema::create('shop_order_items', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('order_id');
            $table->bigInteger('variant_id');
            $table->bigInteger('product_id');
            $table->string('product_name_snapshot', 255);
            $table->string('variant_label_snapshot', 255)->nullable();
            $table->string('sku_snapshot', 255);
            $table->integer('qty');
            $table->integer('unit_price_cents');
            $table->string('tax_class_code', 255)->default('standard');
            $table->decimal('tax_rate_percent', 5, 2);
            $table->integer('tax_amount_cents');
            $table->integer('line_total_cents');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('personalisation')->nullable();
        });

        Schema::create('shop_orders', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('number', 255);
            $table->bigInteger('customer_id')->nullable();
            $table->string('email', 255);
            $table->string('name', 255);
            $table->string('phone', 255)->nullable();
            $table->string('status', 16);
            $table->string('refund_status', 16)->default('none');
            $table->integer('refund_amount_cents')->default(0);
            $table->integer('subtotal_cents');
            $table->integer('shipping_cents');
            $table->integer('tax_cents');
            $table->integer('shipping_tax_cents');
            $table->integer('total_cents');
            $table->string('tax_country_code', 2);
            $table->json('shipping_address_json');
            $table->string('shipping_method_label', 255);
            $table->string('tracking_number', 255)->nullable();
            $table->string('tracking_carrier', 255)->nullable();
            $table->string('stripe_checkout_session_id', 255)->nullable();
            $table->string('stripe_payment_intent_id', 255)->nullable();
            $table->text('notes_internal')->nullable();
            $table->timestamp('placed_at')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->timestamp('shipped_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('fulfilment_method', 16)->nullable();
            $table->string('fulfilment_zone_name', 80)->nullable();
            $table->integer('fulfilment_fee_cents')->nullable();
            $table->string('fulfilment_postcode', 16)->nullable();
            $table->unique(['site_id', 'number'], 'shop_orders_site_id_number_unique');
            $table->index(['site_id', 'status', 'placed_at'], 'shop_orders_site_id_status_placed_at_index');
        });

        Schema::create('shop_orders_numbering', function (Blueprint $table) {
            $table->bigInteger('site_id');
            $table->integer('next_sequence')->default(1);
            $table->timestamp('updated_at')->nullable();
            $table->primary(['site_id']);
        });

        Schema::create('shop_product_category', function (Blueprint $table) {
            $table->bigInteger('product_id');
            $table->bigInteger('category_id');
            $table->boolean('is_primary')->default(true);
            $table->primary(['product_id', 'category_id']);
        });

        Schema::create('shop_product_images', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('product_id');
            $table->string('path', 255);
            $table->integer('sort_order')->default(0);
            $table->string('alt', 255)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['product_id', 'sort_order'], 'shop_product_images_product_id_sort_order_index');
        });

        Schema::create('shop_product_import_receipts', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('idempotency_key', 128);
            $table->json('receipt');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['site_id', 'idempotency_key'], 'shop_product_import_receipts_site_id_idempotency_key_unique');
        });

        Schema::create('shop_product_reviews', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->bigInteger('product_id');
            $table->smallInteger('rating');
            $table->string('title', 80);
            $table->string('body', 2000);
            $table->string('author_name', 60);
            $table->string('author_email_hash', 64)->nullable();
            $table->string('status', 16);
            $table->string('source', 16);
            $table->string('invite_token_hash', 64)->nullable();
            $table->string('ip_hash', 64)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'product_id', 'status'], 'shop_product_reviews_site_id_product_id_status_index');
            $table->index(['site_id', 'status', 'created_at'], 'shop_product_reviews_site_id_status_created_at_index');
        });

        Schema::create('shop_product_variant_images', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('variant_id');
            $table->string('path', 255);
            $table->integer('sort_order')->default(0);
            $table->string('alt', 255)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['variant_id', 'sort_order'], 'shop_product_variant_images_variant_id_sort_order_index');
        });

        Schema::create('shop_product_variants', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('product_id');
            $table->string('sku', 255);
            $table->string('label', 255)->nullable();
            $table->integer('price_cents');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->integer('weight_grams')->nullable();
            $table->unique(['product_id', 'sku'], 'shop_product_variants_product_id_sku_unique');
        });

        Schema::create('shop_products', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('slug', 255);
            $table->string('name', 255);
            $table->text('description')->nullable();
            $table->bigInteger('tax_class_id')->nullable();
            $table->string('status', 16)->default('draft');
            $table->bigInteger('primary_image_id')->nullable();
            $table->boolean('is_ai_seeded')->default(false);
            $table->boolean('is_ai_reviewed')->default(false);
            $table->string('ai_seed_source', 32)->nullable();
            $table->text('ai_prompt_used')->nullable();
            $table->string('ai_model_version', 255)->nullable();
            $table->timestamp('ai_seeded_at')->nullable();
            $table->timestamp('archived_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            // tsvector stored as text (no full-text index) — demo schema only
            $table->text('search_vector')->nullable();
            $table->integer('revision')->default(0);
            $table->boolean('price_from')->default(false);
            $table->json('customer_inputs')->nullable();
            $table->timestamp('published_at')->nullable();
            $table->json('tags')->nullable();
            $table->json('facts')->nullable();
            // SKIPPED gin index shop_products_search_idx (not representable as a Blueprint index)
            $table->unique(['site_id', 'slug'], 'shop_products_site_id_slug_unique');
            $table->index(['site_id', 'status'], 'shop_products_site_id_status_index');
        });

        Schema::create('shop_shipping_rates', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('strategy', 32);
            $table->integer('flat_amount_cents');
            $table->integer('free_threshold_cents')->nullable();
            $table->string('method_label', 255)->default('Standard delivery');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('tiers')->nullable();
            $table->integer('default_weight_grams')->default(500);
            $table->unique(['site_id'], 'shop_shipping_rates_site_id_unique');
        });

        Schema::create('shop_slug_redirects', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('kind', 16);
            $table->string('old_slug', 255);
            $table->string('slug', 255);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['site_id', 'kind', 'old_slug'], 'shop_slug_redirects_site_id_kind_old_slug_unique');
            $table->index(['site_id', 'kind', 'slug'], 'shop_slug_redirects_site_id_kind_slug_index');
        });

        Schema::create('shop_snapshot_current', function (Blueprint $table) {
            $table->bigInteger('site_id');
            $table->bigInteger('snapshot_id');
            $table->timestamp('updated_at')->nullable();
            $table->primary(['site_id']);
        });

        Schema::create('shop_snapshots', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->integer('version');
            $table->json('json')->nullable();
            $table->string('status', 16);
            $table->integer('size_bytes')->nullable();
            $table->integer('build_duration_ms')->nullable();
            $table->integer('product_count')->nullable();
            $table->timestamp('built_at')->nullable();
            $table->string('built_by_job_id', 255)->nullable();
            $table->text('build_error')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('hero_image_url', 2048)->nullable();
            $table->string('hero_alt', 255)->nullable();
            $table->string('hero_height', 255)->default('medium');
            $table->smallInteger('bg_position_y')->default('50');
            $table->string('text_zone', 255)->default('middle-left');
            $table->text('hero_prompt')->nullable();
            $table->string('hero_model', 255)->nullable();
            $table->string('hero_width', 16)->default('boxed');
            $table->boolean('hero_enabled')->default(true);
            $table->string('hero_headline', 60)->nullable();
            $table->string('hero_text_style', 16)->nullable();
            $table->string('hero_accent_word', 60)->nullable();
            $table->json('shared_category_hero')->nullable();
            $table->index(['site_id', 'status', 'built_at'], 'shop_snapshots_site_id_status_built_at_index');
            $table->unique(['site_id', 'version'], 'shop_snapshots_site_id_version_unique');
        });

        Schema::create('shop_stock_reservations', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('variant_id');
            $table->bigInteger('cart_id')->nullable();
            $table->bigInteger('order_id')->nullable();
            $table->integer('qty');
            $table->timestamp('expires_at');
            $table->timestamp('released_at')->nullable();
            $table->timestamp('committed_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['variant_id'], 'shop_stock_reservations_variant_id_index');
        });

        Schema::create('shop_variant_stock', function (Blueprint $table) {
            $table->bigInteger('variant_id');
            $table->integer('on_hand')->default(0);
            $table->timestamp('updated_at')->nullable();
            $table->primary(['variant_id']);
        });

        Schema::create('shop_webhook_events', function (Blueprint $table) {
            $table->string('stripe_event_id', 255);
            $table->string('event_type', 255);
            $table->json('payload_json');
            $table->timestamp('received_at');
            $table->timestamp('processed_at')->nullable();
            $table->text('error')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->primary(['stripe_event_id']);
        });

        Schema::create('site_draft_asset_selections', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('family', 16);
            $table->string('page_type', 64)->default('');
            $table->string('slot', 16)->default('');
            $table->bigInteger('version_id')->nullable();
            $table->bigInteger('created_by_user_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('mode', 8)->default('');
            $table->json('placement')->nullable();
            $table->unique(['site_id', 'family', 'page_type', 'slot'], 'draft_asset_selection_unique');
        });

        Schema::create('site_drafts', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->json('composition');
            $table->bigInteger('updated_by_user_id')->nullable();
            $table->timestamp('updated_at');
            $table->integer('admin_revision')->default(0);
            $table->timestamp('deleted_at')->nullable();
            $table->unique(['site_id'], 'site_drafts_site_id_unique');
        });

        Schema::create('site_enquiries', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('name', 120);
            $table->string('email', 255);
            $table->json('payload')->nullable();
            $table->string('page_type', 40)->nullable();
            $table->string('status', 20)->default('new');
            $table->string('ip_hash', 64)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->json('field_labels')->nullable();
            $table->bigInteger('customer_id')->nullable();
            $table->index(['site_id', 'created_at'], 'site_enquiries_site_id_created_at_index');
            $table->index(['site_id', 'customer_id'], 'site_enquiries_site_id_customer_id_index');
        });

        Schema::create('site_media', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('source', 32)->default('upload');
            $table->string('url', 255);
            $table->string('s3_key', 255)->nullable();
            $table->string('mime_type', 64)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('source_ref', 512)->nullable();
            $table->string('alt_text', 250)->nullable();
            $table->json('metadata')->nullable();
            $table->bigInteger('project_item_id')->nullable();
            $table->string('actor_channel', 16)->nullable();
            $table->string('kind', 16)->default('image');
            $table->string('origin', 16)->default('uploaded');
            $table->integer('width')->nullable();
            $table->integer('height')->nullable();
            $table->string('title', 120)->nullable();
            $table->json('tags')->default('[]');
            $table->text('prompt')->nullable();
            $table->boolean('provisional')->default(false);
            $table->timestamp('deleted_at')->nullable();
            $table->index(['project_item_id', 'created_at'], 'site_media_project_item_created_idx');
            $table->index(['site_id', 'kind'], 'site_media_site_id_kind_index');
            $table->index(['site_id', 'origin'], 'site_media_site_id_origin_index');
            $table->index(['site_id', 'provisional'], 'site_media_site_id_provisional_index');
            $table->index(['site_id', 'source'], 'site_media_site_id_source_index');
        });

        Schema::create('site_media_usages', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_media_id');
            $table->string('usable_type', 255);
            $table->bigInteger('usable_id');
            $table->string('slot', 255);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['usable_type', 'usable_id'], 'site_media_usages_usable_type_usable_id_index');
            $table->unique(['usable_type', 'usable_id', 'slot'], 'site_media_usages_usable_type_usable_id_slot_unique');
        });

        Schema::create('site_personalisation_faces', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('path', 255);
            $table->string('mime_type', 64)->nullable();
            $table->smallInteger('width')->nullable();
            $table->smallInteger('height')->nullable();
            $table->boolean('is_active')->default(false);
            $table->bigInteger('uploaded_by_user_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            // SKIPPED partial index site_personalisation_faces_one_active_per_site (Blueprint cannot express a WHERE predicate)
            $table->index(['site_id', 'created_at'], 'site_personalisation_faces_site_created_idx');
        });

        Schema::create('site_reviews', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('author_name', 80);
            $table->smallInteger('rating');
            $table->text('text');
            $table->string('status', 20)->default('pending');
            $table->string('ip_hash', 64)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['site_id', 'status', 'created_at'], 'site_reviews_site_id_status_created_at_index');
        });

        Schema::create('site_subscriptions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->string('product', 255)->default('managed_content');
            $table->integer('monthly_page_quota')->default(3);
            $table->json('kinds')->default('["service","guide","cost_guide","case_study","hub"]');
            $table->boolean('active')->default(true);
            $table->timestamp('started_at');
            $table->integer('carryover_credit')->default(0);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['site_id'], 'site_subscriptions_site_id_unique');
        });

        Schema::create('site_versions', function (Blueprint $table) {
            $table->id('id');
            $table->bigInteger('site_id');
            $table->integer('version');
            $table->json('composition');
            $table->json('page_revisions');
            $table->timestamp('published_at');
            $table->bigInteger('published_by_user_id')->nullable();
            $table->text('publish_note')->nullable();
            $table->string('actor_channel', 16)->nullable();
            $table->index(['site_id', 'published_at'], 'site_versions_site_id_published_at_index');
            $table->unique(['site_id', 'version'], 'site_versions_site_id_version_unique');
        });

        Schema::create('site_versions_current', function (Blueprint $table) {
            $table->bigInteger('site_id');
            $table->bigInteger('version_id');
            $table->timestamp('updated_at');
            $table->primary(['site_id']);
        });

        Schema::create('sites', function (Blueprint $table) {
            $table->id('id');
            $table->string('business_name', 255);
            $table->string('business_type', 255);
            $table->string('location', 255);
            $table->text('agent_notes')->nullable();
            $table->string('generation_mode', 255)->default('no_site');
            $table->string('status', 255)->default('draft');
            $table->string('theme', 255)->default('trades-bold');
            $table->text('last_error')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('preview_layout', 16)->default('multi_page');
            $table->bigInteger('client_id')->nullable();
            $table->string('preview_domain', 255)->nullable();
            $table->string('preview_brand', 8)->default('a');
            $table->string('custom_domain', 255)->nullable();
            $table->string('custom_domain_status', 16)->nullable();
            $table->string('custom_domain_cf_id', 255)->nullable();
            $table->string('custom_domain_cf_zone', 255)->nullable();
            $table->string('slug', 255)->nullable();
            $table->bigInteger('created_by_user_id')->nullable();
            $table->bigInteger('assigned_to_user_id')->nullable();
            $table->json('design_brief')->nullable();
            $table->json('admin_suggestions')->nullable();
            $table->string('brand_favicon_url', 255)->nullable();
            $table->string('brand_og_url', 255)->nullable();
            $table->boolean('projects_page_enabled')->nullable();
            $table->boolean('honest_project_framing')->nullable();
            $table->json('project_categories')->nullable();
            $table->string('country', 32)->nullable();
            $table->string('image_quality_tier', 20)->default('preview');
            $table->boolean('personalise_enabled')->default(false);
            $table->timestamp('deleted_at')->nullable();
            $table->boolean('home_hero_video_enabled')->default(false);
            $table->string('review_provider', 16)->nullable();
            $table->string('review_place_id', 255)->nullable();
            $table->text('review_source_url')->nullable();
            $table->string('review_place_id_source', 20)->nullable();
            $table->json('reviews_cache')->nullable();
            $table->timestamp('reviews_cache_fetched_at')->nullable();
            $table->string('reviews_cache_status', 16)->nullable();
            $table->text('reviews_cache_error')->nullable();
            $table->string('projects_layout', 32)->default('grid');
            $table->boolean('reviews_show_count_in_hero')->default(true);
            $table->boolean('reviews_show_count_in_summary')->default(true);
            $table->string('home_hero_video_provider', 80)->nullable();
            $table->string('home_hero_video_tier', 8)->nullable();
            $table->text('home_hero_video_prompt')->nullable();
            $table->string('home_hero_video_path', 500)->nullable();
            $table->string('home_hero_video_status', 16)->default('idle');
            $table->timestamp('home_hero_video_last_generated_at')->nullable();
            $table->json('home_hero_scene')->nullable();
            $table->json('home_hero_scene_draft')->nullable();
            $table->boolean('reviews_show_date_in_summary')->default(false);
            $table->string('reviews_hero_badge_mode', 16)->default('on');
            $table->string('home_layout', 64)->default('classic');
            $table->string('logo_size', 32)->default('standard');
            $table->string('header_bg', 9)->nullable();
            $table->smallInteger('logo_margin')->default('0');
            $table->json('review_suppressions')->nullable();
            $table->boolean('native_reviews_enabled')->default(false);
            $table->string('enquiry_notification_email', 255)->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->string('home_hero_video_loop', 16)->nullable();
            $table->string('home_hero_video_poster_path', 255)->nullable();
            $table->string('services_layout', 64)->default('classic');
            $table->string('about_layout', 64)->default('classic');
            $table->string('header_mode', 16)->nullable();
            $table->string('right_action', 16)->nullable();
            $table->string('nav_cta_label', 40)->nullable();
            $table->string('nav_cta_url', 255)->nullable();
            $table->boolean('footer_show_logo')->default(false);
            $table->string('footer_motto', 120)->nullable();
            $table->string('form_style', 16)->nullable();
            $table->string('accent_style', 16)->nullable();
            $table->bigInteger('overlay_logo_concept_id')->nullable();
            $table->string('overlay_logo_size', 16)->nullable();
            $table->string('overlay_glass', 16)->nullable();
            $table->smallInteger('overlay_logo_margin')->nullable();
            $table->string('nav_case', 16)->nullable();
            $table->smallInteger('header_padding')->nullable();
            $table->string('header_shrink', 8)->nullable();
            $table->string('header_fit', 16)->nullable();
            $table->string('nav_cta_target', 8)->nullable();
            $table->string('overlay_inner_scale', 8)->nullable();
            $table->string('purpose', 16)->default('website');
            $table->timestamp('shop_first_purchasable_at')->nullable();
            $table->string('shop_mode', 16)->default('cart');
            $table->string('shop_currency', 3)->default('GBP');
            $table->string('chrome_layout', 64)->default('classic');
            $table->string('brand_image_path', 255)->nullable();
            $table->smallInteger('brand_image_opacity')->default('12');
            $table->string('brand_image_fit', 8)->default('cover');
            $table->string('hero_focus', 8)->nullable();
            $table->string('hero_copy_style', 16)->nullable();
            $table->bigInteger('brand_image_media_id')->nullable();
            $table->string('brand_og_square_url', 255)->nullable();
            $table->string('brand_og_custom_path', 255)->nullable();
            $table->json('default_customer_inputs')->nullable();
            $table->string('shop_nav_style', 16)->nullable();
            $table->boolean('shop_enabled')->default(false);
            $table->string('nav_container_style', 16)->nullable();
            $table->string('nav_container_fill', 16)->nullable();
            $table->json('brand_og_custom_meta')->nullable();
            $table->json('product_tags')->nullable();
            $table->json('auto_tags')->nullable();
            $table->smallInteger('shop_page_size')->nullable();
            $table->string('shop_default_sort', 16)->nullable();
            $table->json('shop_index_blocks')->nullable();
            $table->json('product_fact_groups')->nullable();
            $table->json('fulfilment')->nullable();
            $table->json('reviews_settings')->nullable();
            $table->smallInteger('brand_image_position_y')->nullable();
            $table->string('site_type', 255)->nullable();
            $table->string('region', 255)->nullable();
            $table->string('nav_row_bg', 9)->nullable();
            $table->string('nav_row_pattern', 16)->nullable();
            $table->string('nav_row_image_path', 255)->nullable();
            $table->smallInteger('nav_row_image_opacity')->default('12');
            $table->string('nav_row_image_fit', 8)->default('cover');
            $table->smallInteger('nav_row_image_position_y')->nullable();
            $table->bigInteger('nav_row_image_media_id')->nullable();
            $table->boolean('announcement_enabled')->default(false);
            $table->json('announcement_messages')->nullable();
            $table->string('announcement_bg', 9)->nullable();
            $table->string('nav_row_accent_border', 12)->nullable();
            $table->string('texture_key', 32)->nullable();
            $table->decimal('texture_opacity', 4, 3)->nullable();
            $table->string('texture_image_path', 255)->nullable();
            $table->string('shop_noun', 40)->nullable();
            $table->index(['assigned_to_user_id'], 'sites_assigned_to_user_id_index');
            $table->index(['country'], 'sites_country_index');
            $table->index(['created_by_user_id'], 'sites_created_by_user_id_index');
            $table->unique(['custom_domain'], 'sites_custom_domain_unique');
            $table->index(['overlay_logo_concept_id'], 'sites_overlay_logo_concept_id_index');
            $table->index(['paid_at'], 'sites_paid_at_index');
            $table->unique(['preview_domain', 'preview_brand'], 'sites_preview_domain_preview_brand_unique');
            // SKIPPED partial index sites_reviews_due_idx (Blueprint cannot express a WHERE predicate)
        });

        Schema::create('tax_classes', function (Blueprint $table) {
            $table->id('id');
            $table->string('code', 32);
            $table->string('name', 255);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['code'], 'tax_classes_code_unique');
        });

        Schema::create('tax_rates', function (Blueprint $table) {
            $table->id('id');
            $table->string('country_code', 2);
            $table->bigInteger('tax_class_id');
            $table->decimal('rate_percent', 5, 2);
            $table->date('valid_from');
            $table->date('valid_to')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['country_code', 'tax_class_id', 'valid_from'], 'tax_rates_country_code_tax_class_id_valid_from_index');
        });

        Schema::create('theme_token_presets', function (Blueprint $table) {
            $table->id('id');
            $table->string('name', 255);
            $table->text('description')->nullable();
            $table->json('tokens');
            $table->bigInteger('created_by_user_id')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->unique(['name'], 'theme_token_presets_name_unique');
        });

        Schema::create('users', function (Blueprint $table) {
            $table->id('id');
            $table->string('name', 255);
            $table->string('email', 255);
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password', 255)->nullable();
            $table->string('remember_token', 100)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->text('two_factor_secret')->nullable();
            $table->text('two_factor_recovery_codes')->nullable();
            $table->timestamp('two_factor_confirmed_at')->nullable();
            $table->bigInteger('client_id')->nullable();
            $table->string('role', 255)->nullable();
            $table->string('microsoft_id', 255)->nullable();
            $table->string('upn', 255)->nullable();
            $table->string('tenant_id', 255)->nullable();
            $table->timestamp('last_login_at')->nullable();
            $table->timestamp('role_synced_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->unique(['email'], 'users_email_unique');
            $table->unique(['microsoft_id'], 'users_microsoft_id_unique');
            $table->index(['role'], 'users_role_index');
        });

        Schema::table('before_after_pairs', function (Blueprint $table) {
            $table->foreign(['after_image_id'])->references(['id'])->on('site_media')->onDelete('set null');
            $table->foreign(['before_image_id'])->references(['id'])->on('site_media')->onDelete('set null');
            $table->foreign(['page_id'])->references(['id'])->on('generated_pages')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('business_profiles', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('clients', function (Blueprint $table) {
        });

        Schema::table('editor_agent_approvals', function (Blueprint $table) {
            $table->foreign(['approved_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['requested_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('editor_operation_log', function (Blueprint $table) {
            $table->foreign(['actor_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('external_api_calls', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('set null');
        });

        Schema::table('generated_page_revisions', function (Blueprint $table) {
            $table->foreign(['created_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['page_id'])->references(['id'])->on('generated_pages')->onDelete('cascade');
            $table->foreign(['parent_revision_id'])->references(['id'])->on('generated_page_revisions')->onDelete('set null');
        });

        Schema::table('generated_pages', function (Blueprint $table) {
            $table->foreign(['draft_revision_id'])->references(['id'])->on('generated_page_revisions')->onDelete('set null');
            $table->foreign(['parent_id'])->references(['id'])->on('generated_pages')->onDelete('restrict');
            $table->foreign(['published_revision_id'])->references(['id'])->on('generated_page_revisions')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('hero_versions', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('hero_video_versions', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('imported_media', function (Blueprint $table) {
            $table->foreign(['assigned_page_id'])->references(['id'])->on('generated_pages')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('layout_presets', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('logo_concepts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('previews', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('project_categories', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('project_items', function (Blueprint $table) {
            $table->foreign(['category_id'])->references(['id'])->on('project_categories')->onDelete('set null');
            $table->foreign(['detail_page_id'])->references(['id'])->on('generated_pages')->onDelete('set null');
            $table->foreign(['image_id'])->references(['id'])->on('site_media')->onDelete('set null');
            $table->foreign(['page_id'])->references(['id'])->on('generated_pages')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('projects_page_drafts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_cart_items', function (Blueprint $table) {
            $table->foreign(['cart_id'])->references(['id'])->on('shop_carts')->onDelete('cascade');
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants')->onDelete('cascade');
        });

        Schema::table('shop_carts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_categories', function (Blueprint $table) {
            $table->foreign(['parent_id'])->references(['id'])->on('shop_categories')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_customer_addresses', function (Blueprint $table) {
            $table->foreign(['customer_id'])->references(['id'])->on('shop_customers')->onDelete('cascade');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_customer_magic_links', function (Blueprint $table) {
            $table->foreign(['customer_id'])->references(['id'])->on('shop_customers')->onDelete('cascade');
        });

        Schema::table('shop_customers', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_drafts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['updated_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
        });

        Schema::table('shop_featured_products', function (Blueprint $table) {
            $table->foreign(['product_id'])->references(['id'])->on('shop_products')->onDelete('cascade');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_hero_versions', function (Blueprint $table) {
            $table->foreign(['created_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_inventory_movements', function (Blueprint $table) {
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants')->onDelete('cascade');
        });

        Schema::table('shop_order_items', function (Blueprint $table) {
            $table->foreign(['order_id'])->references(['id'])->on('shop_orders')->onDelete('cascade');
            $table->foreign(['product_id'])->references(['id'])->on('shop_products');
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants');
        });

        Schema::table('shop_orders', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_orders_numbering', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_product_category', function (Blueprint $table) {
            $table->foreign(['category_id'])->references(['id'])->on('shop_categories')->onDelete('cascade');
            $table->foreign(['product_id'])->references(['id'])->on('shop_products')->onDelete('cascade');
        });

        Schema::table('shop_product_images', function (Blueprint $table) {
            $table->foreign(['product_id'])->references(['id'])->on('shop_products')->onDelete('cascade');
        });

        Schema::table('shop_product_import_receipts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_product_reviews', function (Blueprint $table) {
            $table->foreign(['product_id'])->references(['id'])->on('shop_products')->onDelete('cascade');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_product_variant_images', function (Blueprint $table) {
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants')->onDelete('cascade');
        });

        Schema::table('shop_product_variants', function (Blueprint $table) {
            $table->foreign(['product_id'])->references(['id'])->on('shop_products')->onDelete('cascade');
        });

        Schema::table('shop_products', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['tax_class_id'])->references(['id'])->on('tax_classes')->onDelete('set null');
        });

        Schema::table('shop_shipping_rates', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_slug_redirects', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_snapshot_current', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['snapshot_id'])->references(['id'])->on('shop_snapshots')->onDelete('cascade');
        });

        Schema::table('shop_snapshots', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('shop_stock_reservations', function (Blueprint $table) {
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants')->onDelete('cascade');
        });

        Schema::table('shop_variant_stock', function (Blueprint $table) {
            $table->foreign(['variant_id'])->references(['id'])->on('shop_product_variants')->onDelete('cascade');
        });

        Schema::table('site_draft_asset_selections', function (Blueprint $table) {
            $table->foreign(['created_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_drafts', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['updated_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
        });

        Schema::table('site_enquiries', function (Blueprint $table) {
            $table->foreign(['customer_id'])->references(['id'])->on('shop_customers')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_media', function (Blueprint $table) {
            $table->foreign(['project_item_id'])->references(['id'])->on('project_items')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_media_usages', function (Blueprint $table) {
            $table->foreign(['site_media_id'])->references(['id'])->on('site_media')->onDelete('cascade');
        });

        Schema::table('site_personalisation_faces', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['uploaded_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
        });

        Schema::table('site_reviews', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_subscriptions', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_versions', function (Blueprint $table) {
            $table->foreign(['published_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
        });

        Schema::table('site_versions_current', function (Blueprint $table) {
            $table->foreign(['site_id'])->references(['id'])->on('sites')->onDelete('cascade');
            $table->foreign(['version_id'])->references(['id'])->on('site_versions')->onDelete('cascade');
        });

        Schema::table('sites', function (Blueprint $table) {
            $table->foreign(['assigned_to_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['brand_image_media_id'])->references(['id'])->on('site_media')->onDelete('set null');
            $table->foreign(['client_id'])->references(['id'])->on('clients')->onDelete('set null');
            $table->foreign(['created_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
            $table->foreign(['nav_row_image_media_id'])->references(['id'])->on('site_media')->onDelete('set null');
        });

        Schema::table('tax_rates', function (Blueprint $table) {
            $table->foreign(['tax_class_id'])->references(['id'])->on('tax_classes')->onDelete('cascade');
        });

        Schema::table('theme_token_presets', function (Blueprint $table) {
            $table->foreign(['created_by_user_id'])->references(['id'])->on('users')->onDelete('set null');
        });

        Schema::table('users', function (Blueprint $table) {
            $table->foreign(['client_id'])->references(['id'])->on('clients')->onDelete('set null');
        });

    }

    public function down(): void
    {
        Schema::dropIfExists('users');
        Schema::dropIfExists('theme_token_presets');
        Schema::dropIfExists('tax_rates');
        Schema::dropIfExists('tax_classes');
        Schema::dropIfExists('sites');
        Schema::dropIfExists('site_versions_current');
        Schema::dropIfExists('site_versions');
        Schema::dropIfExists('site_subscriptions');
        Schema::dropIfExists('site_reviews');
        Schema::dropIfExists('site_personalisation_faces');
        Schema::dropIfExists('site_media_usages');
        Schema::dropIfExists('site_media');
        Schema::dropIfExists('site_enquiries');
        Schema::dropIfExists('site_drafts');
        Schema::dropIfExists('site_draft_asset_selections');
        Schema::dropIfExists('shop_webhook_events');
        Schema::dropIfExists('shop_variant_stock');
        Schema::dropIfExists('shop_stock_reservations');
        Schema::dropIfExists('shop_snapshots');
        Schema::dropIfExists('shop_snapshot_current');
        Schema::dropIfExists('shop_slug_redirects');
        Schema::dropIfExists('shop_shipping_rates');
        Schema::dropIfExists('shop_products');
        Schema::dropIfExists('shop_product_variants');
        Schema::dropIfExists('shop_product_variant_images');
        Schema::dropIfExists('shop_product_reviews');
        Schema::dropIfExists('shop_product_import_receipts');
        Schema::dropIfExists('shop_product_images');
        Schema::dropIfExists('shop_product_category');
        Schema::dropIfExists('shop_orders_numbering');
        Schema::dropIfExists('shop_orders');
        Schema::dropIfExists('shop_order_items');
        Schema::dropIfExists('shop_inventory_movements');
        Schema::dropIfExists('shop_hero_versions');
        Schema::dropIfExists('shop_featured_products');
        Schema::dropIfExists('shop_drafts');
        Schema::dropIfExists('shop_customers');
        Schema::dropIfExists('shop_customer_magic_links');
        Schema::dropIfExists('shop_customer_addresses');
        Schema::dropIfExists('shop_categories');
        Schema::dropIfExists('shop_carts');
        Schema::dropIfExists('shop_cart_items');
        Schema::dropIfExists('sessions');
        Schema::dropIfExists('projects_page_drafts');
        Schema::dropIfExists('project_items');
        Schema::dropIfExists('project_categories');
        Schema::dropIfExists('previews');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('logo_concepts');
        Schema::dropIfExists('layout_presets');
        Schema::dropIfExists('jobs');
        Schema::dropIfExists('job_batches');
        Schema::dropIfExists('imported_media');
        Schema::dropIfExists('hero_video_versions');
        Schema::dropIfExists('hero_versions');
        Schema::dropIfExists('generated_pages');
        Schema::dropIfExists('generated_page_revisions');
        Schema::dropIfExists('fx_rates');
        Schema::dropIfExists('failed_jobs');
        Schema::dropIfExists('external_api_calls');
        Schema::dropIfExists('editor_operation_log');
        Schema::dropIfExists('editor_agent_approvals');
        Schema::dropIfExists('clients');
        Schema::dropIfExists('cache_locks');
        Schema::dropIfExists('cache');
        Schema::dropIfExists('business_profiles');
        Schema::dropIfExists('before_after_pairs');
    }
};
